package GUI;

import java.awt.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.*;

import sun.audio.AudioPlayer;
import sun.audio.AudioStream;


/**
 *
 * @author Thomas
 */
public class MainFrame{
    JFrame jf;


    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        jf = new JFrame();
        jf.setVisible(true);
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPlay = new javax.swing.JLabel();
        lblOptions = new javax.swing.JLabel();
        lblCredits = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblBattleships = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        jf.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jf.setTitle("Battleships");
        jf.setBackground(new java.awt.Color(51, 51, 255));
        jf.setForeground(java.awt.Color.magenta);
        jf.setMinimumSize(new java.awt.Dimension(780, 520));

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setOpaque(false);

        lblPlay.setBackground(new java.awt.Color(51, 0, 153));
        lblPlay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlay.setIcon(new javax.swing.ImageIcon(".\\src\\Sprites\\PlayBW.png")); // NOI18N
        lblPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPlayMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPlayMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblPlayMouseReleased(evt);
            }
        });

        lblOptions.setBackground(new java.awt.Color(255, 255, 255));
        lblOptions.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblOptions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOptions.setIcon(new javax.swing.ImageIcon("src\\Sprites\\OptionsBW.png")); // NOI18N
        lblOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOptionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOptionsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblOptionsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblOptionsMouseReleased(evt);
            }
        });

        lblCredits.setBackground(new java.awt.Color(255, 255, 255));
        lblCredits.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCredits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCredits.setIcon(new javax.swing.ImageIcon("src\\Sprites\\CreditsBW.png")); // NOI18N
        lblCredits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreditsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCreditsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCreditsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCreditsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblCreditsMouseReleased(evt);
            }
        });

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon("src\\Sprites\\ExitBW.png")); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblExitMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                                        .addComponent(lblOptions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                                        .addComponent(lblCredits, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                                        .addComponent(lblExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(204, 102, 0));
        jPanel2.setOpaque(false);

        lblBattleships.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        lblBattleships.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBattleships.setIcon(new javax.swing.ImageIcon("src\\Sprites\\Battleships.png")); // NOI18N
        lblBattleships.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBattleshipsMouseClicked(evt);
            }
        });
        lblBattleships.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblBattleshipsKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblBattleships, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblBattleships, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addContainerGap())
        );

        lblBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackground.setIcon(new javax.swing.ImageIcon("src\\Sprites\\Preview_143.png")); // NOI18
        lblBackground.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBackground.setMaximumSize(new java.awt.Dimension(1920, 1080));
        lblBackground.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(jf.getContentPane());
        jf.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 804, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 552, Short.MAX_VALUE))
        );

        jf.pack();
    }// </editor-fold>



    private void lblOptionsMouseEntered(java.awt.event.MouseEvent evt) {
        lblOptions.setIcon(new javax.swing.ImageIcon("src\\Sprites\\OptionsWB.png"));
        playSFX("src\\SFX\\Menu_Tick.wav");
    }

    private void lblOptionsMouseExited(java.awt.event.MouseEvent evt) {
        lblOptions.setIcon(new javax.swing.ImageIcon("src\\Sprites\\OptionsBW.png"));
    }

    private void lblPlayMouseEntered(java.awt.event.MouseEvent evt) {
        lblPlay.setIcon(new javax.swing.ImageIcon("src\\Sprites\\PlayWB.png"));
        playSFX("src\\SFX\\Menu_Tick.wav");
    }

    private void lblPlayMouseExited(java.awt.event.MouseEvent evt) {
        lblPlay.setIcon(new javax.swing.ImageIcon("src\\Sprites\\PlayBW.png"));
    }

    private void lblPlayMouseClicked(java.awt.event.MouseEvent evt) {
        playSFX("src\\SFX\\SA2_142.wav");
        System.out.println("ah fuck");
    }

    private void lblBattleshipsKeyPressed(java.awt.event.KeyEvent evt) {


    }

    private void lblBattleshipsMouseClicked(java.awt.event.MouseEvent evt) {
        System.out.println("this is battleships");
    }

    private void lblPlayMousePressed(java.awt.event.MouseEvent evt) {
        lblPlay.setIcon(new javax.swing.ImageIcon("src\\Sprites\\PlayOnPress.png"));
    }

    private void lblPlayMouseReleased(java.awt.event.MouseEvent evt) {
        lblPlay.setIcon(new javax.swing.ImageIcon("src\\Sprites\\PlayWB.png"));
    }

    private void lblOptionsMousePressed(java.awt.event.MouseEvent evt) {
        lblOptions.setIcon(new javax.swing.ImageIcon("src\\Sprites\\OptionsOnPress.png"));
    }

    private void lblOptionsMouseReleased(java.awt.event.MouseEvent evt) {
        lblOptions.setIcon(new javax.swing.ImageIcon("src\\Sprites\\OptionsWB.png"));
    }

    private void lblCreditsMouseEntered(java.awt.event.MouseEvent evt) {
        playSFX("src\\SFX\\Menu_Tick.wav");
        lblCredits.setIcon(new javax.swing.ImageIcon("src\\Sprites\\CreditsWB.png"));
    }

    private void lblCreditsMouseExited(java.awt.event.MouseEvent evt) {
        lblCredits.setIcon(new javax.swing.ImageIcon("src\\Sprites\\CreditsBW.png"));
    }

    private void lblCreditsMousePressed(java.awt.event.MouseEvent evt) {
        lblCredits.setIcon(new javax.swing.ImageIcon("src\\Sprites\\CreditsOnPress.png"));
    }

    private void lblCreditsMouseReleased(java.awt.event.MouseEvent evt) {
        lblCredits.setIcon(new javax.swing.ImageIcon("src\\Sprites\\CreditsWB.png"));
    }

    private void lblCreditsMouseClicked(java.awt.event.MouseEvent evt) {
        playSFX("src\\SFX\\SA2_142.wav");
    }

    private void lblOptionsMouseClicked(java.awt.event.MouseEvent evt) {
        playSFX("src\\SFX\\SA2_142.wav");
    }

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {
        playSFX("src\\SFX\\SA2_142.wav");
    }

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {
        playSFX("src\\SFX\\Menu_Tick.wav");
        lblExit.setIcon(new javax.swing.ImageIcon("src\\Sprites\\ExitWB.png"));
    }

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {
        lblExit.setIcon(new javax.swing.ImageIcon("src\\Sprites\\ExitBW.png"));
    }

    private void lblExitMousePressed(java.awt.event.MouseEvent evt) {
        lblExit.setIcon(new javax.swing.ImageIcon("src\\Sprites\\ExitOnPress.png"));
    }

    private void lblExitMouseReleased(java.awt.event.MouseEvent evt) {
        lblExit.setIcon(new javax.swing.ImageIcon("src\\Sprites\\ExitWB.png"));
    }


    //play Sound effects
    public static void playSFX(String filepath){
        InputStream SFX;
        try{
            SFX = new FileInputStream(new File(filepath));
            AudioStream audio = new AudioStream(SFX);
            AudioPlayer.player.start(audio);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error music");
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBattleships;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblOptions;
    private javax.swing.JLabel lblPlay;
    // End of variables declaration
}
